# Generated by Django 3.2.25 on 2024-08-13 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('CID', models.IntegerField(help_text="Content's primary key.", primary_key=True, serialize=False)),
                ('Category', models.CharField(choices=[(1, 'Anime'), (2, 'Manga')], default='1', help_text='Content category', max_length=1)),
                ('Name', models.CharField(help_text='Content name', max_length=200)),
                ('Score_avg', models.FloatField(default=0.0)),
                ('Genres', models.CharField(blank=True, help_text="Content's Genres", max_length=200)),
                ('Ctype', models.CharField(blank=True, help_text='Manga type (Oneshot, shounen,...)', max_length=200)),
                ('Episodes', models.IntegerField(blank=True, help_text='Number of published chapters.')),
                ('Aired', models.CharField(blank=True, help_text='Publish date.', max_length=200)),
                ('Last_update', models.DateField(blank=True, help_text='Date of last published chapter.')),
                ('Producers', models.CharField(blank=True, help_text='None for Manga.', max_length=500)),
                ('Licensors', models.CharField(blank=True, help_text='Companies that have the rights to translate, publish, and distribute the manga.', max_length=200)),
                ('Studios', models.CharField(blank=True, help_text='Tteams that assist the main artist with tasks.', max_length=200)),
                ('Source', models.CharField(blank=True, help_text='Light novel, Book, etc. (e.g Original).', max_length=200)),
                ('Duration', models.CharField(blank=True, help_text='None for Manga.', max_length=200)),
                ('Rating', models.CharField(blank=True, help_text='Manga age rate (e.g. safe).', max_length=200)),
                ('Ranked', models.IntegerField(default=0, help_text='.')),
                ('Favorites', models.IntegerField(default=0, help_text='Number of user have this manga in their favorite list.')),
                ('Watching', models.IntegerField(default=0, help_text='Reading.')),
                ('Completed', models.IntegerField(default=0, help_text='Completed.')),
                ('On_Hold', models.IntegerField(default=0, help_text='On Hold.')),
                ('Dropped', models.IntegerField(default=0, help_text='Dropped.')),
                ('Plan_to_Watch', models.IntegerField(default=0, help_text='Plan to Read.')),
                ('Picture', models.ImageField(default=0, help_text='Content cover picture.', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('OID', models.IntegerField(help_text='Order id.', primary_key=True, serialize=False)),
                ('Order_date', models.DateField(help_text='Date of the order.')),
                ('Status', models.CharField(help_text='Order status (e.g. Shipped).', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('UID', models.IntegerField(help_text='User id', primary_key=True, serialize=False)),
                ('Username', models.CharField(help_text='Username', max_length=255)),
                ('Role', models.CharField(choices=[('admin', 'admin'), ('new_user', 'new_user'), ('longtime_user', 'longtime_user'), ('user', 'user'), ('VIP', 'VIP')], default='new_user', help_text='User role.', max_length=20)),
                ('Email', models.CharField(help_text='Email address', max_length=255)),
                ('Password', models.CharField(help_text='Password', max_length=255)),
                ('Date_of_birth', models.DateField(blank=True, help_text='Date of birth')),
                ('Profile_picture', models.ImageField(blank=True, help_text='Profile picture', upload_to='')),
                ('Registration_date', models.DateField(help_text="Account's registration date")),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score_10', models.IntegerField(default=0)),
                ('Score_9', models.IntegerField(default=0)),
                ('Score_8', models.IntegerField(default=0)),
                ('Score_7', models.IntegerField(default=0)),
                ('Score_6', models.IntegerField(default=0)),
                ('Score_5', models.IntegerField(default=0)),
                ('Score_4', models.IntegerField(default=0)),
                ('Score_3', models.IntegerField(default=0)),
                ('Score_2', models.IntegerField(default=0)),
                ('Score_1', models.IntegerField(default=0)),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_data', to='wibu_catalog.content')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('PID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(help_text='Name of the product.', max_length=255)),
                ('Price', models.FloatField(default=0, help_text="Product's price.")),
                ('Description', models.TextField(blank=True, help_text="Product's description.", max_length=500)),
                ('Ravg', models.FloatField(default=0, help_text="Product's average rating.")),
                ('Picture', models.ImageField(blank=True, help_text="Product's picture.", upload_to='')),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='wibu_catalog.content')),
            ],
        ),
        migrations.CreateModel(
            name='orderitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1, help_text='Number of ordered products.')),
                ('Buy_price', models.FloatField(help_text='Price at the time of Ordered.')),
                ('OID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='wibu_catalog.order')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='wibu_catalog.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='wibu_catalog.user'),
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('Notification_id', models.AutoField(help_text='Naughtyfication id.', primary_key=True, serialize=False)),
                ('Message', models.TextField(help_text="Notification's message.", max_length=500)),
                ('Date', models.DateField()),
                ('Ntype', models.CharField(blank=True, max_length=255)),
                ('Is_read', models.BooleanField(default=False)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='wibu_catalog.user')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cmt', models.TextField(blank=True, help_text='User comment about the product.', max_length=500)),
                ('Rate', models.IntegerField(blank=True, help_text='User rating of the product.')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='wibu_catalog.product')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='wibu_catalog.user')),
            ],
        ),
        migrations.CreateModel(
            name='favorite_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[(1, 'Watching'), (2, 'Completed'), (3, 'On_Hold'), (4, 'Dropped'), (5, 'Re_Watching'), (6, 'Plan_to_Watch')], default='1', help_text='User status with this content.', max_length=1)),
                ('Progress', models.IntegerField(default='0', help_text="User's progress (e.g. chapter01).")),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favlist', to='wibu_catalog.content')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favlist', to='wibu_catalog.user')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField(help_text="User's comment.", max_length=255)),
                ('Date_of_cmt', models.DateField(blank=True, help_text="Comment's date.")),
                ('Likes', models.IntegerField(default=0, help_text='Number of likes.')),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wibu_catalog.content')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wibu_catalog.user')),
            ],
        ),
        migrations.CreateModel(
            name='score_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='10', help_text="User's score of this content.")),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoreslist', to='wibu_catalog.content')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoreslist', to='wibu_catalog.user')),
            ],
            options={
                'unique_together': {('UID', 'CID')},
            },
        ),
    ]
