# Generated by Django 3.2.25 on 2024-08-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0003_auto_20240813_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notification_id',
            new_name='notificationId',
        ),
    ]
