# Generated by Django 3.2.12 on 2024-08-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0002_auto_20240815_1228'),
        ('wibu_catalog', '0005_auto_20240813_2312'),
    ]

    operations = [
    ]
