# Generated by Django 3.2.25 on 2024-08-18 11:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0006_merge_0002_auto_20240815_1228_0005_auto_20240813_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='content',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, help_text='Content cover picture.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Product's picture.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profilePicture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Profile picture', max_length=255, null=True),
        ),
    ]
