# Generated by Django 4.2.15 on 2024-08-16 09:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0007_alter_content_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Product's picture.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profilePicture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Profile picture', max_length=255, null=True),
        ),
    ]
