# Generated by Django 4.2.15 on 2024-08-19 03:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0008_alter_product_picture_alter_users_profilepicture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='content',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='movie3.jpg', help_text='Content cover picture.', max_length=255, null=True),
        ),
    ]
