# Generated by Django 4.2.15 on 2024-08-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0007_auto_20240818_1824'),
        ('wibu_catalog', '0009_alter_comments_options_alter_content_picture'),
    ]

    operations = [
    ]
