# Generated by Django 5.1 on 2024-08-21 09:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0010_merge_20240819_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='movie3.jpg', help_text='Content cover picture.', max_length=255, null=True),
        ),
    ]
