# Generated by Django 4.2.15 on 2024-08-22 04:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0010_merge_20240819_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='movie3.jpg', help_text='Content cover picture.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.AutoField(help_text='Order id.', primary_key=True, serialize=False),
        ),
    ]
