# Generated by Django 4.2.15 on 2024-08-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0011_alter_content_picture'),
        ('wibu_catalog', '0011_alter_content_picture_alter_order_oid'),
    ]

    operations = [
    ]
