# Generated by Django 3.2.25 on 2024-08-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0012_content_rewatching_alter_favoritelist_status'),
        ('wibu_catalog', '0012_merge_20240823_0900'),
    ]

    operations = [
    ]
