# Generated by Django 3.2.25 on 2024-08-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0013_merge_20240827_2157'),
        ('wibu_catalog', '0013_merge_20240827_2158'),
    ]

    operations = [
    ]
