# Generated by Django 5.1 on 2024-08-30 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0014_comments_parent_comments_userlikes'),
        ('wibu_catalog', '0014_merge_20240829_1335'),
    ]

    operations = [
    ]
