# Generated by Django 5.1 on 2024-08-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0013_merge_20240828_0846'),
        ('wibu_catalog', '0015_merge_20240830_1047'),
    ]

    operations = [
    ]
